### PR TITLE
Open changeset I can comment on

### PR DESCRIPTION
**Pull request by eseliger**
This is a changeset that is ready to receive comments.

[_Created by Sourcegraph batch change `eseliger/test-comment`._](https://sourcegraph.test:3443/users/eseliger/batch-changes/test-comment)

### CODE REVIEW

**Comment by eseliger** [comment]
## Testing to comment on all changesets

If this works, a comment should be created on `GitHub`, `GitLab` and `BitbucketServer`. :pray:

**Comment by eseliger** [comment]
## Testing to comment on all changesets

If this works, a comment should be created on `GitHub`, `GitLab` and `BitbucketServer`. :pray:

**Comment by eseliger** [comment]
## Testing to comment on all changesets

If this works, a comment should be created on `GitHub`, `GitLab` and `BitbucketServer`. :pray:

**Comment by eseliger** [comment]
# 🐴 The horse returns

**Comment by eseliger** [comment]
The final revenge of the 🐴

**Comment by eseliger** [comment]
The 🐴 is back!

**Comment by eseliger** [comment]
The 🐴 is back!

**Comment by eseliger** [comment]
abcdef

**Comment by eseliger** [comment]
# The horse greets you all 🐴

**Comment by eseliger** [comment]
Testcomment

**Comment by eseliger** [comment]
Test comment 2

**Comment by eseliger** [comment]
test123

**Comment by eseliger** [comment]
asd

**Comment by chrispine** [comment]
If we don't want to merge this, and if we're done with testing, let's close this PR.

**Pull request closed without merging**
